### ISSUE TITLE
Feature: maxed hero icon or filter?

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#10]
Any chance to mimic the Maxed hero icon from the game?  put right on their image for easy visibility? just like the game does?  or perhaps a filter for it?

**Comment by hook** [comment]
This already exists.

**Comment by user23498723452** [comment]
I'm sorry I didn't clarify, but the icons are not present in the Team section, where I think it would be very helpful.

**Comment by hook** [comment]
Oh yeah I did implement it but it was sitting on my laptop that I usually update offline, it should be in there now.
