### ISSUE TITLE
Crossbones synergies are incorrect

### ISSUE THREAD

**Issue by JPags** [hook/champions#100]
...fromId(CHAMPION.CROSSBONES, [
        ...fromStars(3, 5, [ CHAMPION.CAPTAINAMERICA, CHAMPION.CAPTAINAMERICAWWII, CHAMPION.FALCON ], { effectId: EFFECT.CRITICAL_RATE }),
        ...fromStars(4, 5, [ CHAMPION.WINTERSOLDIER, CHAMPION.BLACKWIDOW ], { effectId: EFFECT.CRITICAL_DAMAGE }),
    ]),

Should be ..fromStars(3, 5, [ CHAMPION.WINTERSOLDIER,

I have a 3* wintersoldier and I get 25% Critical damage from him when I match him with Crossbones

**Comment by JPags** [comment]
Not sure if its related to the same issue, but when I build a team and I have crossbones, WinterSoldier, and Black Widow, I think that I should have 50% critical damage (25% black widow and 25% for winter soldier) but the end result only shows 25% critical damage.

**Comment by hook** [comment]
when it lets you use one of two for one effect (multiple portraits next to each other in game), it will only recognize one at most.
