### ISSUE TITLE
Drax Synergies

### ISSUE THREAD

**Issue by dschrimpsher** [hook/champions#102]
Drax is missing synergies.  I have a 4 star and a  5 star and they have

7% Critical Rate with Ronan
5% Perfect Block with Star Lord
5% Perfect Block with Agent Venom
25% Critical Damage with Gamora

You only have
Perfect Block with Star Lord
GAMORA Critical Damage
AGENT VENOM Perfect Block

**Comment by dschrimpsher** [comment]
I have a fix for this locally in a branch but I don't have permission to push.  You guys can fix it or let me do a PR.  either way its a one line fix. 

in src/data/synergies.js  line 64-69

 ```
 ...fromId(CHAMPION.DRAX, [
        ...fromStars(2, 5, [ CHAMPION.RONAN ], EFFECT.CRITICAL_RATE),
        ...fromStars(2, 5, [ CHAMPION.STARLORD ], EFFECT.PERFECT_BLOCK),
        ...fromStars(2, 5, [ CHAMPION.GAMORA ], EFFECT.CRITICAL_DAMAGE),
        ...fromStars(3, 4, [ CHAMPION.AGENTVENOM ], EFFECT.PERFECT_BLOCK),
    ]),
```

**Comment by dschrimpsher** [comment]
![screenshot_2017-01-19-21-35-59](https://cloud.githubusercontent.com/assets/4982278/22134817/9db72b9c-de8f-11e6-8b0d-249ee8456354.png)

**Comment by hook** [comment]
accepted PR, thanks :)
