### ISSUE TITLE
Hood ready for release?

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#106]
It doesn't seem like you have released Hood.  Are you waiting for some stats?  http://playcontestofchampions.com/champion-spotlight-hood/

Unduped, 3*/1/1 info:

 Synergies:
Crime Bosses Lv 2 , +4% armor and Crit Hit Chance     -  JF
Enemies Lv 2 , +6% Crit Rate                                  -  DV, Punisher
Teammates Lv 2 ,+4% Perfect Block Chance          - IP,Loki

Dash Back and Hold Block:
While Invisible, the Hood deals 89% increased Critical Damage and his attacks ignore 75% armor

Critical Hits:
48% Change to Stagger the Opponent...

Special Attack 1:
Shocks the opponent, dealing 105% of the Hood's Attack as Energy Damage over 7.5 sec

Special Attack 2:
Hexes the opponent, reducing Ability Accuracy by 44%

Special Attack 3:
Attack deals 50% increased damage
100% chance to inflict Bleed, dealing 100% of your attack as direct damage over 6 seconds.

**Comment by hook** [comment]
he is added but his synergies are wrong

**Comment by hook** [comment]
Synergies are now to be kept track of [here](https://github.com/hook/champions/wiki/Synergy-Champions)

It is a public wiki that anyone can update, and I'll do my best to keep the app up to date. This way we also have 1 canonical place for all of this data that can be hard to track!
