### ISSUE TITLE
Add 2* Thor (Jane Foster)

### ISSUE THREAD

**Issue by elgaberino** [hook/champions#108]
I don't have an un-duped version because I pulled two simultaneously. I don't know if that affects base statistics.

Duped (sig 1) 2*/1/1:

Synergies
Thor, Romance Lv. 1 (+3% Power Gain)

Base health is 689, attack 50

Signature Ability 
All-Mother's Blessing guarantees critical hits and 58.07 critical damage rating against stunned opponents

I'm a bit vague on whether the following are affected by masteries or duplication so bear with me if they are:
Challenge Rating 30
Critical Rating 315
Critical Damage Rating 413
Armor Penetration 69
Block Penetration 69
Armor Rating 439
Block Proficiency 2,188
Critical Resistance 106

Special 1 deals 67.5 energy damage over 8 seconds
Special 2 deals 70 energy damage over 8.50 seconds

21% chance to stun shocked opponents with any strike

Passive: "Mystical influences grant this Champion 1405.56 increased Energy Resistance," whatever that means

**Comment by hook** [comment]
added
