### ISSUE TITLE
Add 2* Old Man Logan and X-23

### ISSUE THREAD

**Issue by dracu777** [hook/champions#109]
They were given in a (possibly one-time) Logan crystal

**Comment by elgaberino** [comment]
Yes please

**2-star X23 Base Attributes** Rank 1/1 not awakened
572 Health
52 Attack
Challenge Rating: 20
Critical Ratin: 563
Critical Damages Rating: 686
Armor Rating: 33
Block Proficiency: 2,303
Synergy with Wolverine (Blue Team) _or_ Old Man Logan, "Family Lv.1" all champs +4% health

**2-star Old Man Logan Attributes** Rank 1/1 not awakened
Health: 611
Attack: 49
Challenge Rating: 20
Critical Rating: 478
Critical Damage Rating: 563
Armor Rating: 33
Block Proficiency: 2,845
Synergy with Wolverine (Blue Team) "Enemies Lv.1" all champs gain +85 Critical Rating

**Comment by hook** [comment]
Synergies are now to be kept track of [here](https://github.com/hook/champions/wiki/Synergy-Champions)

It is a public wiki that anyone can update, and I'll do my best to keep the app up to date. This way we also have 1 canonical place for all of this data that can be hard to track!
