### ISSUE TITLE
Feature: 3* arena infinite streak filter/team build

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#11]
Sorry, I haven't tested the 4* version, but I'm not sure if it works on the 3* arena.   The 3* arena seems to work well with maxed 2* heroes.  Although I can't say it it's perfect.

**Comment by hook** [comment]
This would need complex parameters,  that I don't have defined yet.  What would the rules be for choosing teams?

**Comment by user23498723452** [comment]
I was thinking maxed 2*, since that is a strong recommendation from folks.  But I've not done enough tests myself to see if the "best" method" would also use some Tier 1 and Tier 2 heroes.

The first 4 fights - anything goes.  Up through fight 20 it is Easy if you use maxed 2*.  After that is when it changes to Medium.

**Comment by hook** [comment]
For 3★ arena, using just 2★ champions is best. That's the arena I play (no thanks 5mil+ cutoffs) and using 1★s would be a waste of time.

4★ arena is more complex with infinite streaks if people don't have a roster of 4★ 5/50s. That's the logic that I need to be well defined if I'm going to set up a building mode for those teams.

**Comment by user23498723452** [comment]
Sorry, I said Tier, when I meant Rank.  The 3* arena has some type of logic where you should pull in a lower Rank hero (or two or three?) to prevent from triggering a Hard match.  I think that is what "infinite streak" in 3* looks like.  The Medium fights are always doable.  I haven't had time to determine if there is a consistent pattern as to which fight requires a hero rank change.   But it is clear that doing so helps the fights to stay in Medium.

**Comment by hook** [comment]
Lets move this discussion to #18
