### ISSUE TITLE
Synergies

### ISSUE THREAD

**Issue by frumplejoon** [hook/champions#111]
3* Scarlet Witch does not have any synergies with Phoenix
3* Hood synergy with Joe Fixit is "Crime Bosses" (+Armor and Crit Rating)
3* Ghost Rider does not have any synergies with Punisher
3* Karnak does not have any synergies with Ms. Marvel or Captain Marvel
3* Gambit does not have any synergies with Magneto
3* Rogue does not have any synergies with Deadpool
3* Iron Fist (Immortal) is missing the Friends synergy with Luke Cage (+Armor)

Are the synergy numbers going to be updated with the new rating system?

**Comment by hook** [comment]
Haven't had a ton of time to devote to this app lately, but I'll get back to it once work settles down!

I'll try to get on these (other than crime bosses because i really dont know the criteria is for its application) some time this week!

Thanks

**Comment by The-Retronaut** [comment]
Hood and Dormammu Synergies are off too. Also when is psylocke being added?

**Comment by hook** [comment]
Added Psylocke.

I'll look into a better solution for keeping track of synergy changes.

**Comment by The-Retronaut** [comment]
@hook dormammu and hood synergize with each other, not Guilly

**Comment by hook** [comment]
Synergies are now to be kept track of [here](https://github.com/hook/champions/wiki/Synergy-Champions)

It is a public wiki that anyone can update, and I'll do my best to keep the app up to date. This way we also have 1 canonical place for all of this data that can be hard to track!

**Comment by The-Retronaut** [comment]
Thanks Hook! Will update now.
