### ISSUE TITLE
Max Level failure

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#120]
I have some users reporting max level failure.

When you change a champion to rank 2, the available levels should be 20 for 4star, 35 for 5star.

Right now, if you change to any rank, the maximum levels available = 10.

**Comment by hook** [comment]
Well thats not right!!!

**Comment by JasonJW** [comment]
Come chat with us.

I think we can help improve your prestige calc slightly.
http://join.simians.tk

**Comment by user23498723452** [comment]
Is "number" a keyword that shouldn't be used for variables?  https://github.com/hook/champions/search?utf8=%E2%9C%93&q=Number&type=

**Comment by hook** [comment]
Good catch, i was moving to use Number instead of parseInt but forgot i had a named `Number` component!

**Comment by hook** [comment]
Fixed, please verify its fixed for you and I'll close!

**Comment by user23498723452** [comment]
It is fixed, based on very quick testing.
