### ISSUE TITLE
Add obb 813362 champs

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#122]
Vulture (or vulture_movie)
Spider-Man MCU (or spiderman_movie)

**Comment by hook** [comment]
I'm still out if commission. I'll accept a pull request, otherwise it's gonna be a few weeks.

**Comment by BillyNate** [comment]
@hook Where do you get the portrait images from usually?

**Comment by hook** [comment]
I pull them out of the .obb after updating on my phone. (I'm on android and use adb to pull the new file to local machine, and then decompress the .obb file)

**Comment by BillyNate** [comment]
I managed to pull the images out of the .obb by using [ZArchiver](https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver) (seemed faster/easier to me than pulling the whole .obb and decompress it).
They're included in PR #133, but I could not find the `fullsize` images in the .obb, can these be found somewhere else?
