### ISSUE TITLE
Pls Add Spider-Man (Stark-Enhanced) & Punisher 2099

### ISSUE THREAD

**Issue by Feuerforst** [hook/champions#124]
Could you pls add 
2* Version of  Spider-Man (Stark-Enhanced)  
3* Version of Spider-Man (Stark-Enhanced)
3* Version of Punisher 2099

**Comment by PlayNaked** [comment]
Also:
4* Spider-Man (Stark-Enhanced)
5* Spider-Man (Stark-Enhanced)
4* Punisher 2099
5* Punisher 2099
**5* Elektra**

**Comment by hook** [comment]
added
