### ISSUE TITLE
PI max

### ISSUE THREAD

**Issue by ken-sipe** [hook/champions#143]
Power index caps at 10000, but r4 5*s can definitely exceed that, especially with suicide masteries.

**Comment by user23498723452** [comment]
Now with 6*,  this should be addressed. @Luiz012

**Comment by Luiz012** [comment]
I'll try to fix this

**Comment by user23498723452** [comment]
This search should help:

`https://github.com/hook/champions/search?q=10000&unscoped_q=10000`

**Comment by Luiz012** [comment]
Thx man. I raised to 20k, I guess that its enough by now

**Comment by user23498723452** [comment]
fyi,  5* can also exceed 10k.  https://theclassadvantage.com/prestige-charts/

**Comment by Luiz012** [comment]
Fixed
