### ISSUE TITLE
Team list issues?

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#15]
1.  I cannot seem to figure out how to get the full synergy list to appear for a team.   (it only shows up to 3 synergies)

2.  Firefox and Chrome have different behaviors.  In FF I can select a synergy to show the heroes relevant.  That doesn't work in Chrome.  In Chrome, you can highlight heroes to change the synergy %'s  using red text to show the difference. 
3.  Also, it seems like the "weights" you can assign for synergies don't work like I would expect.  For example, if I raise  "Block Proficiency" to 100%, I would expect the app to show me the best team for "Block Proficiency".  Is that not correct?  (I've made sure nothing else is near 100%)

Can these items be standardized and/or fixed?

**Comment by hook** [comment]
3. If you raise Block Proficiency to 100% it will value that the highest. It still takes other things into consideration like multiple types (depending on your settings) and champion PI.

The algorithm does work as expected, although it might not be 100% intuitive at all times.

**Comment by user23498723452** [comment]
I will confirm that is does not build ANY Block Proficiency teams when I select "Defensive" and then move "Block Proficiency" to 100%.

Here is my CSV:


Id,Stars,Rank,Level,Awakened,Pi
"abomination",2,2,1,3,0
"antman",4,2,6,0,0
"antman",2,3,30,7,0
"blackbolt",3,3,30,8,0
"blackbolt",2,3,30,17,0
"blackpanther",4,3,30,0,0
"blackpanther",3,4,40,24,1691
"blackpanther",2,2,1,5,0
"blackpanther",1,2,20,0,0
"blackwidow",4,3,30,0,2287
"blackwidow",3,3,1,10,0
"blackwidow",2,3,30,15,0
"captainamerica",2,3,30,8,0
"captainmarvel",3,1,1,0,0
"colossus",3,4,40,16,1807
"colossus",2,3,30,4,0
"colossus",1,2,20,0,0
"cyclops",3,3,5,0,0
"cyclops",2,3,1,12,0
"daredevilnetflix",2,3,10,0,0
"deadpoolxforce",3,1,1,0,0
"deadpoolxforce",2,2,1,0,0
"drax",2,3,1,12,0
"drstrange",4,3,30,0,0
"drstrange",3,4,40,2,1624
"electro",3,4,40,0,0
"elektra",3,1,1,0,0
"gamora",4,3,30,0,0
"gamora",3,4,40,1,0
"gamora",2,3,30,8,0
"gamora",1,2,20,0,0
"guillotine",3,2,16,0,0
"guillotine",2,2,20,1,0
"hawkeye",3,4,40,9,1632
"hawkeye",2,3,30,19,0
"hulk",2,3,30,4,0
"hulk",1,2,20,0,0
"hulkbuster",3,4,40,8,1782
"hulkbuster",2,2,1,5,0
"ironfist",3,4,40,32,1777
"ironfist",2,3,30,16,0
"ironman",3,1,10,0,0
"ironman",2,3,30,12,0
"ironpatriot",3,1,10,0,0
"juggernaut",4,3,30,0,2169
"juggernaut",3,1,1,16,0
"juggernaut",2,2,1,12,0
"magik",3,1,2,8,0
"magik",2,2,20,4,0
"magneto",3,1,4,8,0
"magneto",2,2,1,5,0
"punisher",3,4,40,80,0
"punisher",2,3,1,7,0
"rhino",2,2,1,14,0
"rocket",2,2,1,1,0
"ronan",2,2,1,6,0
"scarletwitch",2,3,30,4,0
"scarletwitch",1,2,20,0,0
"spidergwen",4,1,1,0,0
"spiderman",2,3,30,13,0
"spiderman",1,2,20,0,0
"spidermanblack",3,1,1,0,0
"starlord",2,3,30,11,0
"storm",3,2,20,0,0
"storm",2,3,30,5,0
"superiorironman",3,2,9,0,0
"superiorironman",2,3,1,4,0
"thevision",3,3,30,8,1086
"thevision",2,3,1,5,0
"thor",3,2,20,0,0
"thor",2,3,30,5,0
"ultron",3,1,10,8,0
"ultron",2,3,30,13,0
"unstoppablecolossus",3,1,10,0,0
"unstoppablecolossus",2,3,30,24,0
"venom",3,1,1,0,0
"venompool",3,1,10,8,0
"vision",2,2,1,8,0
"vision",1,2,20,0,0
"warmachine",3,1,10,0,0
"wintersoldier",3,2,1,16,0
"wintersoldier",2,2,1,14,0
"wolverine",3,4,40,8,0
"wolverine",2,3,30,15,0
"wolverine",1,2,20,0,0
"yellowjacket",3,4,40,9,1728
"yellowjacket",2,3,30,3,0

**Comment by hook** [comment]
1. Yes it is non unique synergies counted overall. 

2. Try with different duplicates settings.  I'm guessing it's not picking the multiple mystic because that's lowering the internal team rating too much.

**Comment by hook** [comment]
So it doesn't look like anything is broken,  keep in mind that other settings (like duplicates) are also affecting chosen teams.
