### ISSUE TITLE
Missing Champs

### ISSUE THREAD

**Issue by billybobaloo** [hook/champions#150]
I have no idea how to update this thing, so I'm putting this info here.

I have the following 2* champs which are not listed in the tool:
Science: Joe Fixit, Red Hulk
Skill: Crossbones, Kingpin, Ragnarok Thor
Cosmic: Hela, Kamala Khan
Tech: Green Goblin
Mystic: Dormammu, The Hood

Also, as someone already mentioned, Medusa is Cosmic not Skill.

**Comment by xyphoz** [comment]
missing champs: 
2-morningstar
2-bpcw
2-thorragnarok

**Comment by Kognac14** [comment]
Killmonger
Hulk Ragnarok
Void
Sentry

**Comment by user23498723452** [comment]
@billybobaloo Please close this out

**Comment by Kognac14** [comment]
I do not know how to close it or I would have
