### ISSUE TITLE
Adding 6* champs??

### ISSUE THREAD

**Issue by xyphoz** [hook/champions#153]
Now that the 6* champions have been out for a while, it'd be awesome to have them added here. 
I realise it might be a bit of work, and it may change a lot of the interface (filters, synergies across tiers...)

**Comment by user23498723452** [comment]
I also would like to see this functionality added.
I honestly think the best way to alter the portraits is to have "6 *",  not "******".  And obviously alter the other star levels in the same fashion.

Much more readable AND this leaves you room to consider placing the sig level on the portraits.  :)

**Comment by user23498723452** [comment]
@xyphoz Please close this issue out.
