### ISSUE TITLE
Champion PI is completely off

### ISSUE THREAD

**Issue by timplunkett** [hook/champions#16]
3* 3/30 unduped Scarlet Witch:
In game 1025 PI
In app 1200 PI

3* 3/1 unduped Winter Solider
In game 734 PI
In app 910 PI

Does it have to do with masteries? And if so, wouldn't the in-game score be higher?

I can provide other data points if that would help, but hopefully I'm just doing something wrong that is obvious to you.

**Comment by hook** [comment]
Yes I try to make general approximations, specific just to stars/ranks/levels. The game uses a lot of hidden stats to calculate actual PI and masteries affect the calculations on top of those stats, so for now this is the best way to do it.

This is why I give a guess and then allow the user to specify what the actual PI is if they want accurate stats.

**Comment by timplunkett** [comment]
That makes a lot more sense. I wasn't sure if you had backwards engineered an older version of the app to find the exact method of computation. If it's guesswork, you did a good enough job, and I'm going to close this.

Thanks for all your work!
