### ISSUE TITLE
Found a way to cleanup the add stars 6* entry

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#165]
This will make the 6* add button in line with the other stars,  by shrinking each button equally.

[CSS fix for Add Stars 6* button](https://i.imgur.com/OfOFd84.png)

If someone could handle the pull request,  that would be awesome.  Test it in chrome yourself.

**Comment by hook** [comment]
you can add a pull request directly in the browser!

**Comment by user23498723452** [comment]
Can I delete all of my previous repos? Without impacting anything?
