### ISSUE TITLE
2 Star Champions

### ISSUE THREAD

**Issue by Xigro** [hook/champions#173]
You should add MODOK (who was available trough Marvel Insider) to the 2* champions and remove the following ones:
Cosmic: Captain Marvel, Hyperion, Ms. Marvel
Tech: Howard the Duck, Iron Patriot, Nebula, Yondu
Mutant: Archangel, Beast, Cable, Cyclops (Blue Team), Gambit, Iceman, Nightcrawler, Psylocke, Rogue
Skill: Elektra, Falcon, Gwenpool, Karnak, Taskmaster
Science: She-Hulk
Mystic: Doctor Voodoo, Mordo, Mephisto

**Comment by ronin712** [comment]
I can confirm this.  I have 72 2*s, including MODOK and I have none of the ones listed as being unavailable as a 2*.

**Comment by Xigro** [comment]
So today I opened a 2* xmen crystal. There was Cable, Nightcrawler and Beast available.
Plus, I've seen a 2* medusa on a kang's team in arena, and there will be a Crystal with Infinity War characters including Nebula and Falcon

**Comment by Neverglow** [comment]
With some of the latest funky crystals they offered in the last couple months, we've seen a lot of new 2*s.
Here are a few I currently own, who are not listed in the roster list:
2* Howard the Duck
2* Omega Red
2* Red Skull
2*Vision (AoU)

Also, in alphabetical order, Hood is actually listed In-Game as "The Hood" and appears in the T's. Lame, I know

**Comment by user23498723452** [comment]
@Neverglow Don't worry, they were incorrectly removed, and we've been assured they will be restored soon. @hook

**Comment by user23498723452** [comment]
@Xigro Can you please close this issue?
