### ISSUE TITLE
Calculate all of the catalysts needed to get all champs to next rank

### ISSUE THREAD

**Issue by timplunkett** [hook/champions#19]
There's a [rank-up tracker](https://docs.google.com/spreadsheets/d/1MqxXYHT1JUhYQ7ePEVx_On3rOCIVEn14aC75itTNJdE/edit#gid=1641644314) that can do this, but it'd be nice to have one place to track champions.

Unlike PI, this is a known formula.

**Comment by hook** [comment]
I'll look at maybe adding something to the roster view.

Maybe a menu toggle to show needed resources for all shown upgrades needed, displayed like the upgrade details in champion edit mode.

**Comment by hook** [comment]
I do have upgrade stats shown in each Champion's detailed view.

I think what I'll do is add a roster option to show upgrade amounts needed and then show a box in the same manner as the Champion details with combined totals of all needed resources. This will change depending on the filter currently applied. Also thinking about doing a additional option of only showing resources needed for Champions that are immediately upgradable, ie. with a maxed out level, but not rank.

**Comment by hook** [comment]
Added a roster option to show current needed upgrade resources. This is affected by the filter you have on your roster (show only the upgrades for the champions you care about).
