### ISSUE TITLE
Teams page won't permit selecting 6*

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#194]
You cannot select 6* on the Teams page.  I think the link below points to the relevant code.

https://github.com/hook/champions/blob/634618737ecfadca57f53549d7bba869aaad5c55/src/view/App/TeamsMenu.jsx#L169

**Comment by Luiz012** [comment]
Fixed

**Comment by user23498723452** [comment]
Sweet @Luiz012 ,  confirmed working!
