### ISSUE TITLE
Teams settings page limits champ PIs

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#195]
At the bottom of the Teams settings page,  there are sliders for PI values,  which prevent high PI champs from being selectable.

Max Champion PI and Max Team PI, both need to be raised.

![selection_115](https://user-images.githubusercontent.com/17534291/42726143-cd66b93e-875d-11e8-9f4d-c9466ce6f7b8.png)

**Comment by Luiz012** [comment]
Fixed

**Comment by user23498723452** [comment]
well done @Luiz012 !
