### ISSUE TITLE
Proper balance of PI in Arena teams

### ISSUE THREAD

**Issue by rocha** [hook/champions#21]
Very often arena teams are being constructed with a combination of PI that makes the team very weak. For example, one champion with 2000 and the two other ones with 400. 

Since matchmaking using the combined team PI, it is likely that enemy teams are composed of at least two of its member will have a larger PI than the player's team. This match in most of the time very hard to win.

It would be great if the team creator takes individual PI combinations per team, so either at least two of the team champions have similar PI.

**Comment by hook** [comment]
Lets have this discussion in #18, as that's the intended place for arena team building algorithms for now.
