### ISSUE TITLE
Missing Champions not showing Synergies in Build

### ISSUE THREAD

**Issue by Gekkoyolo** [hook/champions#22]
Team building for a 5 person quest not fully showing all synergies. In "Modify" champions are missing, such as Iron Man Sup, Daredevil, Captain America etc, meaning that "Build" does not show the best team.

**Comment by hook** [comment]
Do you have them saved in another AW or AQ quest already? It doesn't allow overlapping quest teams,  since they get locked in while  in use.

**Comment by Gekkoyolo** [comment]
Hi,
I'm missing 5 champions. I have dissolved Arena, Quest 3-4-5, AW attack and defense, and AQ. Nowhere to be found (might be usefull to add an "dissolve all" option)

**Comment by hook** [comment]
Are they addable from the roster add menu? Are they being filtered possibly? Send me a CSV export via email and I'll do some digging!

**Comment by Gekkoyolo** [comment]
Yep, addable and added, no filters activated. Sending it now!

**Comment by hook** [comment]
It looks like the roles are set to an old and invalid value. I'll post a fix tonight, but for now you can either delete and re-add or manually set all of the roles on the missing champions.

**Comment by hook** [comment]
Updated, please let me know if it works now, and I'll close this!

**Comment by Gekkoyolo** [comment]
The missing champions are still not appearing in "extras" when i try and do it manually, and now "build" doesn't seem to work: the cog is turning but no result

**Comment by hook** [comment]
Well that's worse!

**Comment by hook** [comment]
Try it now,  it should be fixed

**Comment by Gekkoyolo** [comment]
Problem solved! it all works perfectly. Thanks a bunch, the best coc tool available!
