### ISSUE TITLE
Inclusion of Masteries

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#23]
I didn't notice a request for this yet.  I'm sure there are lots of things that make this seem like a mountain,  but perhaps picking on a specific mastery at a time would make it easy.

Masteries impact PI and synergies.  There are some spreadsheets out there that give some indication of the impact(s)  but I'm not sure anything is science.

A key mastery is Block Proficiency,  used to create the so-called zero damage team.  But there are others,  possibly simpler in nature.

Any consideration on trying to implement support for these in the synergy selection?

**Comment by hook** [comment]
Hi,

I'm very aware of how masteries affect PI and synergies. PI calculation is done by tallying all stats (hp, attack, armor, crit, block, etc) after things like masteries and other effects.

Unfortunately these stats per champion are completely hidden from us, and the formula for calculating PI based on them is therefore not reverse-engineerable. There really isn't a way to accurately solve the PI for any given champion, including a user's masteries, so in my opinion it's not a very valuable thing to include in the tool for now.

I do have some things that allow you to value certain synergy stats above others, and you can always use the synergy graph page to view something like block proficiency to get a perfect block team with your roster.

I hope this helps!

**Comment by hook** [comment]
Closing this for now. If we ever get detailed info on stats/masteries/PI then I can implement it. Until then its just guessing at a moving target.
