### ISSUE TITLE
Print / export / share my teams

### ISSUE THREAD

**Issue by jdell64** [hook/champions#24]
Hey guys, love the app!

One of the things I would like to be able to do is print, export, or email my teams to myself. Sometimes I make these teams at home, and as I'm out an about, I have a few minutes, but don't remember my teams.

Also, have you thought about a mobile app (can of worms I'm sure).

**Comment by hook** [comment]
So first for the mobile app, I would do this if I migrated to React,  but that's not gonna happen too soon (maybe in the future still).

**Comment by hook** [comment]
As for exporting teams, the team page is printable,  I recommend printing to PDF and loading that later. I made sure that printing works well. 

If that doesn't work, is there a format that you think would work especially well?

**Comment by jdell64** [comment]
Oh, I guess to be honest I never tried just printing the page.

I was thinking just of exporting to csv or something though. I like to be able to email myself the list or something:

    captainamerica(3*),wintersoldier(4*),ironman(3*)

Maybe it's too niche, but I know I'd like it.

**Comment by hook** [comment]
So give printing a shot first and see if that's what you're looking for.

I could possibly add a print option to the menu that would just do the browsers print so that it's obvious that I support it.

**Comment by jdell64** [comment]
Print will work, but the Champs are rather large and it page breaks weird.

On Friday, April 15, 2016, Gabriel Hook <notifications@github.com> wrote:

> So give printing a shot first and see if that's what you're looking for.
>
> I could possibly add a print option to the menu that would just do the
> browsers print so that it's obvious that I support it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hook/champions/issues/24#issuecomment-210613030>
>


-- 

--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by jdell64** [comment]
Also, what framework are you using ATM? I have minor chops, maybe I could help you migrate to something else (you mentioned React).

**Comment by hook** [comment]
I'm using Mithril right now which is a VDOM framework much like React. I would prefer staying in the same style of app and use something like React Native to do the apps themselves. I know how to do it and I've done it before on another project, but it's also a bit of work to do the conversion.

I probably will do it but just not right now!

**Comment by hook** [comment]
Handled in #48 now
