### ISSUE TITLE
mark synergie in modification mode

### ISSUE THREAD

**Issue by minigraphx** [hook/champions#25]
I Modification it would be nice to see which champions have a synergy.
Example:
I create a Team, one champ in it and the ones with synergies would have a glow (colored border?) on it.
When there are two champions in the Team, champions that would have synergies with either of it would glow. 

Step 2:
The Synergy which is given has a small symbol like it has in the map - so that we could see which synergy is given to the team.

**Comment by hook** [comment]
I'll look into this idea, it sounds pretty good. The only thing I think I'd have to deal with would be if there are a lot of effects, so possible icon runoff.

I am assuming you mean that we are getting these indicators when selecting either an open spot or replacing a team member with the clickling interface (not drag&drop).

**Comment by minigraphx** [comment]
yeah, right

**Comment by hook** [comment]
Added, it now shows the current +effects for adding that character to the team.

![image](https://cloud.githubusercontent.com/assets/234299/16175439/84f2e7c8-35a1-11e6-964f-ab9598ee840a.png)
