### ISSUE TITLE
create teams with champions that are not teamed

### ISSUE THREAD

**Issue by minigraphx** [hook/champions#26]
i like to build some teams by hand, and than it would be nice if i could klick to build teams, but m own teams stay there - so the rest is build

**Comment by hook** [comment]
I'll set something up so that the user can lock teams for arena, and then build with all remaining.

**Comment by hook** [comment]
Added lockable teams when in arena mode.

To lock a team go into modify mode, apply the lock icon to the team(s) you want.

Rebuild and it will have you locked teams at the top of the list.

Dissolve to clear everything or uncheck the lock to rebuild without the team.

Enjoy :)
