### ISSUE TITLE
Immortal Iron Fist

### ISSUE THREAD

**Issue by SupreamWeasle** [hook/champions#27]
You can get a 3 star/ 4 star / 5 star Immortal Iron Fist now from crystals. Can we have the 3 star and 5 star turned on?

**Comment by hook** [comment]
Do you know the synergies for each?

**Comment by SupreamWeasle** [comment]
5 star should be the same as the 4 star (most of them are). I am doing a little research for the 3 star version.

**Comment by fatpixel** [comment]
3-star synergies:  
![img_3836](https://cloud.githubusercontent.com/assets/196628/14935581/4abd5544-0e8b-11e6-8555-0cc8efc9cd13.PNG)

4-star synergies:  
![img_3837](https://cloud.githubusercontent.com/assets/196628/14935584/8e1cd90e-0e8b-11e6-842e-5774091cd198.PNG)

**Comment by SupreamWeasle** [comment]
thanks Fatpixel

**Comment by hook** [comment]
Added

**Comment by SupreamWeasle** [comment]
thanks :)
