### ISSUE TITLE
October 2020 Champion Updates

### ISSUE THREAD

**Issue by jakekapitz** [hook/champions#287]
October 2020 champions (Red Goblin, Cosmic Ghost Rider, Punisher 2099 tune up) need to be added.

@Luiz012 Creating issue to avoid any duplication of effort; I can start putting a PR request together for these, though would just be the EN -- unless you've already started doing so?

**Comment by Luiz012** [comment]
Hi, I won't have time this month to add these. Can you please add them?

**Comment by jakekapitz** [comment]
Sure thing -- will get on it today.

**Comment by Luiz012** [comment]
Thank you
