### ISSUE TITLE
Feature: Show Team PI (without synergy bonus)

### ISSUE THREAD

**Issue by minigraphx** [hook/champions#3]
it would be fine to see the Team PI, and probably Order by Team PI

**Comment by hook** [comment]
Showing the team pi is doable but I'll have to figure out a nice way to do it view wise. I'll look into how good a feature sorting by overall PI is!

**Comment by hook** [comment]
Right now they are ordered by the strength of the team as per the algorithm picking teams.

**Comment by hook** [comment]
Showing Team PI now
