### ISSUE TITLE
Problem with export .csv function

### ISSUE THREAD

**Issue by gravius** [hook/champions#30]
Hi!
First of all thank for the app! It's really great and I love it!

I'm writing you because I've been experiencing a small problem lately. Once I populate my list of champion I try to export it to the csv file in order to use the list in different devices, but nothing happens, apart from the loading circle next to the mouse.
I'm using Microsoft Edge on Windows 10. Is there a compatibility issue?

Thanks a lot in any case for the great app and for the assistance!

**Comment by hook** [comment]
Looking into this.

**Comment by gravius** [comment]
Hi,
Thanks! Just to let you know that today I've re-entered all my heroes using chrome and I managed to export them in csv without any problem!

Get Outlook for iOS




On Thu, May 12, 2016 at 11:48 AM -0700, "Gabriel Hook" <notifications@github.com> wrote:












Looking into this.

**Comment by hook** [comment]
Looks like CSV export/import is set up properly, hopefully it was just an old bug. I have unit tests for this so I'm gonna close this now.
