### ISSUE TITLE
Synergies off

### ISSUE THREAD

**Issue by Kaldron** [hook/champions#32]
![screenshot_2016-06-02-20-06-56](https://cloud.githubusercontent.com/assets/19721687/15767566/e2e4d57c-28fd-11e6-8849-23d98e9153a5.png)

I noticed that there is a synergy change for Hulkbuster with both SIM and IM. It is a + life family synergy, not perfect block as stated in character profile.

![screenshot_2016-06-02-20-10-37](https://cloud.githubusercontent.com/assets/19721687/15767592/27b86eca-28fe-11e6-8e20-a5db4690d6c0.png)

Is also off on syergy map, though I assume those are tied together

**Comment by Kaldron** [comment]
Is also off on syergy map, though I assume those are tied together

**Comment by timplunkett** [comment]
Do you have a 3* hb to check the synergies?

**Comment by Kaldron** [comment]
On Fri, Jun 10, 2016, 4:02 PM Tim Plunkett <notifications@github.com> wrote:

> Do you have a 3* hb to check the synergies?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hook/champions/issues/32#issuecomment-225315915>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ASzt18h6rswblUye12szT1GPkw5yBGObks5qKe0KgaJpZM4ItJ4Y>
> .
>
3 star and 2 star

>

**Comment by timplunkett** [comment]
so 4* is health +6, is it the same for 3* ?

**Comment by Kaldron** [comment]
3 star is health +5%

**Comment by hook** [comment]
Updated, thanks guys!
