### ISSUE TITLE
Stun Synergy She-Hulk -> Daredevil

### ISSUE THREAD

**Issue by Alsciende** [hook/champions#38]
There's a mistake on this synergy. It's not the same as Black Widow -> Hulk. It is "+15% Stun Activation Chance" (as a 4 stars), and works on any Stun, not only Special Attacks. Currently the tooltip incorrectly states "Chance to Stun on special attacks".

http://community.kabam.com/forums/showthread.php?645759-She-Hulk-Champion-Spotlight

![2016-06-29 11_02_55-champions](https://cloud.githubusercontent.com/assets/391974/16446788/9fcb0f4e-3de9-11e6-8c9a-76640b213c76.png)

**Comment by hook** [comment]
I should have different icons for the 2 types of stuff effect then. Ideas? Maybe a stun swirl inside of a l3 icon for the specials one?

**Comment by Alsciende** [comment]
Actually you have the correct icon. It's the one used in-game. Maybe you could keep this icon and rename the synergy "Stun Activation Chance". It is the expression used by Kabam.

**Comment by hook** [comment]
It's correct, but also confusing to use the same icon for 2 effects only in this case. I changed the crit icons for that reason to precision/cruelty variants

**Comment by JasonJW** [comment]
@hook The tool lists SheHulk as 25% Stun, which is incorrect per my clan.  They are saying that 4star SH gets 15%

**Comment by hook** [comment]
Split into 2 types of stun.
