### ISSUE TITLE
Feature: Creating Teams with Champions that have roundabout same PI

### ISSUE THREAD

**Issue by minigraphx** [hook/champions#4]
When the champions are not maxed, it would be nice to create teams with similar PI for Arena, not 1 strong, 2 weak.

Probably you could implement this in the customization Options ?

**Comment by hook** [comment]
I have been looking into some sort of sandbagging algorithm, possibly evaluating a team based on the synergies it has, but ignoring the pi of one member (so that we get the best team, but we effectively ignore the weakest). It's on my short todo list right now.

**Comment by depo23** [comment]
Maybe assigning a different weight to the PI slider in settings? Actually now it seems like the Build function _almost_ ignores the PI limits...even though the new "Modify" function helps a lot now ;-)

**Comment by hook** [comment]
The PI range is actually for the entire team,  I can probably make that more clear in addition to doing a champion specific range

**Comment by depo23** [comment]
yes! I believe it would be more accurate and reliable when you want to make
teams with champs within a certain range.

2016-03-04 17:21 GMT-03:00 Gabriel Hook <notifications@github.com>:

**Comment by hook** [comment]
I have a fix for the unclear PI range offline, I'll sync it later today.

**Comment by depo23** [comment]
Awesome, man! Thank you for taking the time and always make this better ;-)

**Comment by hook** [comment]
I didn't sync it yet, thank me once I do :smile:

**Comment by hook** [comment]
Finally added it, now theres champion and team PI range settings!

**Comment by hook** [comment]
PI range issues have been addressed, and 4 star arena teams should be discussed in #18.

**Comment by depo23** [comment]
Great addition! Now...thanks :-D

**Comment by hook** [comment]
:+1:
