### ISSUE TITLE
Update Champs to account for new Synergies

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#42]
1) Black Bolt
Cosmic Supremacy with Kamala Khan OR Ronan
Friends with Spider-Man OR Cyclops
Nemesis with Kang
Rival with Hulk

2) War Machine
Friends with Hulkbuster
Enemy with Black Panther
Enemy with Hawkeye
Teammates with Black Widow

3) Dr. Strange
Friends with Thor OR X23
Friends with Spider-Man
Teammates with Scarlet Witch
Teammates with Black Bolt

4) Magneto (red)
Nemesis with Cyclops or 90's Cyclops
Rival with Storm
Enemy with Wolverine
Friends with Magik

5) 90s Cyclops
Teammates with Storm
Nemesis with Magneto
Mutant Agenda with Colossus & Wolverine

**Comment by hook** [comment]
Please list known ★s and the synergy effects and I'll get on it.

**Comment by JasonJW** [comment]
Beast 
Masterminds (+15 Attack on Combo of 15+ hits) - Superior Iron Man, Black Panther Classic.

Missing SIM.
Also Missing Masterminds (new) in the Legend

**Comment by hook** [comment]
Updated masterminds/beast.

**Comment by hook** [comment]
There's an absurd amount of changes, will need help finding all of them!!

**Comment by KChung54** [comment]
Is there an example of how you want the info presented?

**Comment by hook** [comment]
*Either screenshots of champions' synergies or something like:*

**Black Bolt 2★**

Champion(s) | Effect
---|---
Kamala Khan & Ronan  | Cosmic Supremacy
Spiderman & Cyclops | Armor

**Black Bolt 3★**

Champion(s) | Effect
---|---
Kamala Khan & Ronan  | Cosmic Supremacy
Spiderman & Cyclops | Armor
Kang | Attack
Hulk | Critical Damage

**Black Bolt 4★**

Champion(s) | Effect
---|---
Kamala Khan & Ronan  | Cosmic Supremacy
Spiderman & Cyclops | Armor
Kang | Attack
Hulk | Critical Damage

*Or if you want a shorthand to compress ★ ranges.*

**Black Bolt**

★ | Champion(s) | Effect
---|---|---
2-4 | Kamala Khan & Ronan  | Cosmic Supremacy
2-4 | Spiderman & Cyclops | Armor
3-4 | Kang | Attack
3-4 | Hulk | Critical Damage

*which looks like this in an issue*

```md
**Black Bolt**

★ | Champion(s) | Effect
---|---|---
2-4 | Kamala Khan & Ronan  | Cosmic Supremacy
2-4 | Spiderman & Cyclops | Armor
3-4 | Kang | Attack
3-4 | Hulk | Critical Damage
```

*As a rule, any champion with a 4★ and 5★ has the same synergies in both.*

**Comment by KChung54** [comment]
Hmm.  Ok - I'll try the screen shot route - that way, you get the % benefit of the synergy as well..?

**Comment by hook** [comment]
Screen shots are fine. I don't actually need the % because those are calculable using the type of effect and the tier of the synergy's source champion (ie, a 4★ with an attack synergy will be 6%, and I pull that value out when I need it).

**Comment by biancachez** [comment]
CAP WW2 now has an internal synergy with Guillotine (as opposed to just external)

![1821259990626083360-account_id 1](https://cloud.githubusercontent.com/assets/12396854/17636460/2565dc5e-60ab-11e6-8c83-5b6880c70b41.png)

Jane Foster (THOR) now has an internal synergy with Joe Fix It

![3279553210821432894-account_id 1](https://cloud.githubusercontent.com/assets/12396854/17636475/4dabb6ac-60ab-11e6-96f5-40a0be89a59a.png)

**Comment by hook** [comment]
Updated. Could you check if the Cap WW2 to Guilly synergy exists for 3★? I don't have one of her so I'd updating blind on this one 😄

**Comment by KChung54** [comment]
Yes - 3 star Cap WW2 synergy with Guilly is Friends Lv. 2 for +5% Armor

3 star Guilly’s synergy w/WW2 Cap is Teammates Lv.2, good for +4% Perfect Block Chance

**Comment by hook** [comment]
Also the thor jane foster, I already validated wolverine.

**Comment by KChung54** [comment]
The 3 star versions of Cap WW2 and Jane Foster do not have synergies.

**Comment by biancachez** [comment]
Thank you! I see the Qs have been answered, I think @KChung54 meant no synergies between 3* Jane Foster and Joe Fix It - which is accurate.

**Comment by Kaldron** [comment]
Found a synergy missing on Magneto (Marvel Now). Has outgoing synergy of nemesis with black bolt on 4*. Not present on 3* though.

**Comment by hook** [comment]
@Kaldron which is the effect? I think nemesis isn't always +attack%. If you can please add in a screenshot so I can be sure I'm adding the correct synergy.

Thanks!

**Comment by nskraus** [comment]
The synergy isn't there for a 3*

![screenshot_20160827-103030](https://cloud.githubusercontent.com/assets/3312706/18029045/2a04b0a8-6c42-11e6-869a-1045bc8362cf.png)
![screenshot_20160827-103037](https://cloud.githubusercontent.com/assets/3312706/18029050/30b73100-6c42-11e6-96f7-bd29fffa38bf.png)

**Comment by hook** [comment]
Yeah, I get that, I want to see what effect is added in the 4* 😄

**Comment by Kaldron** [comment]
![screenshot_2016-08-26-22-27-32](https://cloud.githubusercontent.com/assets/19721687/18029074/ffa4f34e-6c42-11e6-868f-36b52770e89f.png)

**Comment by nskraus** [comment]
![screenshot_20160827-103001](https://cloud.githubusercontent.com/assets/3312706/18029076/069cbe2a-6c43-11e6-8bc6-91b84784cbec.png)
![screenshot_20160827-103010](https://cloud.githubusercontent.com/assets/3312706/18029078/0bd8ecc4-6c43-11e6-9f57-b9011d79f731.png)

**Comment by hook** [comment]
Thank's added. Should be up in a few minutes!

**Comment by hook** [comment]
I'm gonna close this issue. Let's create an issue per synergy update, that way I'll track them a little better and not let them get lost in a big thread.
