### ISSUE TITLE
Synergy page cannot select multiple champs on desktop

### ISSUE THREAD

**Issue by nskraus** [hook/champions#43]
On these pages http://hook.github.io/champions/#/synergy/stars/4 you can select up to 5 champs on a tablet and see the percentages you get for that team, but on desktop if you click a second champ it deselects the first one.

**Comment by hook** [comment]
You can! First you can drag to select a region. Second you can hold shift to add to your current selection. Thi you can hold control to toggle selections. Hope that helps :)

**Comment by nskraus** [comment]
Yes, thank you! I tried by holding down command but not shift.
