### ISSUE TITLE
Save different groups of arena teams

### ISSUE THREAD

**Issue by nskraus** [hook/champions#44]
I have two different strategies in arenas depending on how long I'm playing for. If only for a short time, I run through just my 4.40/5.50 champs to get the most points quickly, and dont take synergies into account as much, just trying to keep teams balanced. However if I'm grinding, which is usually for an event, it is better to pair a 4.40+ champ with 2 3.30s so that you don't get a 3* in your matchup (more arena combat points for same group of 4*s), which often happens with 3 3.30s. During this run I'm also looking for as many synergies as I can get. Another potential bonus -- this would also help with #24 I believe.

**Comment by hook** [comment]
I'll look into import/export for all teams so you can switch between sets, maybe something else

**Comment by hook** [comment]
Gonna close this as it's basically the same issue as #24 once I get it done.
