### ISSUE TITLE
Feature: Manual team mode

### ISSUE THREAD

**Issue by depo23** [hook/champions#5]
Just a suggestion to this great tool:
- the "manual mode" to create and test your own team synergies !

;-)

**Comment by hook** [comment]
Do you have an idea on how you would do that interface wise? 

I want to avoid using modals but a pop-up on each team position is probably the cleanest way.

**Comment by depo23** [comment]
Yes! I imagined a 3 to 5 empty boxes interface. 

With the ability to select your champ from a single or multiple rows pop-up, with horizontal scroll.
I had clearly in my mind when I posted here. Let me sketch a mock-up ;-) Will post it soon!

**Comment by depo23** [comment]
![hook-m1](https://cloud.githubusercontent.com/assets/16704359/12855292/b2de2e58-cc25-11e5-8d50-427e7a813e1b.jpg)
![hook-m2](https://cloud.githubusercontent.com/assets/16704359/12855291/b2dd911e-cc25-11e5-8473-688b266dfbc6.jpg)

**Comment by depo23** [comment]
That's how it could look like, and here 2 ideas for selecting...sorry it's very basic for now, but if you like we can fine tune all details some more ;-)

![hook-select-2](https://cloud.githubusercontent.com/assets/16704359/12855488/e0e68c54-cc26-11e5-9a9d-2a4b825275cf.jpg)
![hook-select1](https://cloud.githubusercontent.com/assets/16704359/12855489/e0eb3998-cc26-11e5-87b3-c1e0619b86b2.jpg)

**Comment by hook** [comment]
Yeah that's the most straightforward way (how I was thinking to do it myself), its the champion picking that's the trickiest part! Maybe a toggle-able edit mode so you can add/replace/swap/remove champions once the teams have been generated. I would want to show add/replace synergy changes to a team while picking too since that makes the feature useful.

Both of those popup mockups look nice, but I think they work best for high res. I would probably just do a near-fullscreen modal so that it works well on mobile where I have a lot of traffic. The old version of my app had popups like these and I like the look, but it makes rendering tricky once you're on a super small screen.

**Comment by depo23** [comment]
Yes. I got your point. Then a modal responsive is the perfect solution ! The lightbox way.

**Comment by hook** [comment]
i like that cross column interface visually! It's too bad it makes things complicated once the screen is scrolled or tiny (although I can handle scrolling manually). Also showing synergy team diffs is something I think is valuable when selecting a team member.

**Comment by depo23** [comment]
Visually the vertical crossing the horizontal is nice...but I guess it's the functionality that makes this tool so great ! So I guess a little design compromise there would not bother the users. Keeping it simple and straight.

**Comment by depo23** [comment]
...and by the way, the tool usability is fantastic and intuitive! Really well designed!

**Comment by hook** [comment]
Thanks :smile: 

I've tried to keep out modals and other stuff so far, to keep interaction super simple and consistent, so I'll look at all of my options, including pushing to a new screen for a single team edit mode (sort of like champion edit mode).

**Comment by depo23** [comment]
Sure, that could be another solution! Also a way to replicate something already familiar to users ;)

**Comment by depo23** [comment]
Anyway thanks for welcoming my suggestion! 3.0 will rock :D

**Comment by hook** [comment]
Working on it [here...](http://hook.github.io/champions/#/teams/edit)

I just need to add +- synergy diff visuals and then apply the changes. Have source/target selections working.

**Comment by depo23** [comment]
That's AWESOME !

**Comment by hook** [comment]
Check it again, I have it selecting and working with the team building, I just have to commit changes at this point.

**Comment by hook** [comment]
Manual team mode implemented.

Quick description:

- An extra champion can be added to the current unfinished team or swapped with any other team member.
- Already made teams can be dissolved to reclaim champions.
- Single champions can be dropped from the unfinished team.
- Team members from any team can be swapped.

The difference in team changes will be shown for any swap/addition/removal so you can tell if you are improving your group.

**Comment by depo23** [comment]
Wow ! Great job man. This is really helpful for testing teams :-) Thank you so much for taking the time to create the new team mode!!! Greetings *
