### ISSUE TITLE
Unable to select several champs in custom team building

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#50]
For example, I cannot choose my Cyclops to add into a Quest team.  I am missing about half of my 4* roster from the 4* selection list.  Could this have to do with recent renames of some of these champs?

To be clear,  all champs appear properly on the roster pages.  But not for the Team Build section.

UPDATE:  Invalid issue - Caused by filtering out Willpower champs.

**Comment by hook** [comment]
Glad you figured it out :)
