### ISSUE TITLE
Venompool Synergy: Missing Family

### ISSUE THREAD

**Issue by slick10084** [hook/champions#52]
Thanks for this tool!

Venompool seems to be missing the "Family" synergy he has with Agent Venom & Symbiote Spiderman - "All Champions gain +x% health"

**Comment by hook** [comment]
Is this only available at 4 stars? I don't have a Venom Pool to verify with.

**Comment by slick10084** [comment]
I have a 3 & 4 star version and can confirm its there for both of those. According to this link the 5 star has it also. 

http://www.marvelsynergy.com/champions/venompool



Btw it's a synergy that activates with either/or symb spiderman/agent venom. Not double bonus for both in case that helps or makes a difference.

**Comment by hook** [comment]
Thanks got it! Please let me know if you find any others :smile:
