### ISSUE TITLE
Importing / Exporting

### ISSUE THREAD

**Issue by stevwatsn** [hook/champions#56]
I absolutely love this Champions tool that has been put together.  And, I may be looking at this from way out in left field and missing this one, but each time I try and import or export .csv files, it appears to do nothing for me. It definitely does not bring up any dialog box to choose a .csv file.  Are these commands being updated currently?

**Comment by hook** [comment]
It's probably a browser issue. Could you tell me what Operating system/browser you are using and I'll see if I need to do anything extra to support it!

**Comment by stevwatsn** [comment]
Windows 10, the latest Internet Explorer (11?), and if it matters, Office 2016. I will check to see if there may be a pop up issue. Doubtful, but who knows. 
-Steve
Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by stevwatsn** [comment]
it DOES work in latest version of Chrome.
Steve

**Comment by hook** [comment]
Alright, I have it working in chrome/ie/edge/firefox/opera. Please let me know if this work for you and I'll close the issue.

**Comment by stevwatsn** [comment]
I will not have a chance to test until Monday. I am satisfied with you closing it now. Thank you. 
-Steve
Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
