### ISSUE TITLE
5* Spiderman showing different prestige than mutamatt calculator

### ISSUE THREAD

**Issue by nskraus** [hook/champions#58]
Not a big deal, but my 5* 4.55 sig 30 spidey is showing as 5477 in mutamatt's calculator but 5462 in my champion list. Short of stripping my masteries, is there another way to determine what his prestige really is to help you guys with another data point?

**Comment by nskraus** [comment]
So I ended up wiping my masteries for a different reason, and figured I would provide you the data points to, hopefully, help hone the precision of the algorithm. Most of the numbers are spot on, or just slightly off, but some of them are way off. Here's screenshots of my champs, and exported csv from your site so you can see sig levels.
![screenshot_20160825-215800](https://cloud.githubusercontent.com/assets/3312706/17996098/892dd8e8-6b1b-11e6-9346-5150701fc981.png)
![screenshot_20160825-215655](https://cloud.githubusercontent.com/assets/3312706/17996097/892c27aa-6b1b-11e6-82d1-1eacc5d9dc0a.png)
![screenshot_20160825-215645](https://cloud.githubusercontent.com/assets/3312706/17996096/892aeb60-6b1b-11e6-90bc-c40cb73ff58e.png)
![screenshot_20160825-215634](https://cloud.githubusercontent.com/assets/3312706/17996099/892ea08e-6b1b-11e6-910e-fa9bf39825b6.png)
[champions.txt](https://github.com/hook/champions/files/438657/champions.txt)

**Comment by hook** [comment]
My data from matt's calculator was stale. I ended up just writing a tool so I can import his prestige calculations a lot more easily.

Oh and I updated *champions*
