### ISSUE TITLE
Missing ability statements

### ISSUE THREAD

**Issue by mcoc-collector** [hook/champions#59]
Captain Marvel's bio indicates L1 has "True Damage"
Her ability shortlist describes this ability as "Direct Damage"

The closest thing in your list is "True Strike"

**Comment by mcoc-collector** [comment]
Power Sting

**Comment by JasonJW** [comment]
Profiles for Abomination, Captain Marvel, Hulk, Iron Man, Yellowjacket.

[Hook.zip](https://github.com/hook/champions/files/465004/Hook.zip)

**Comment by hook** [comment]
Added, and I changed ability true strike to Direct Damage with appropriate description.

**Comment by JasonJW** [comment]
Power Steal
Limbo
