### ISSUE TITLE
Move Build tuning button

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#6]
Could you move the Build settings/tuning button in the lower left corner into the upper right menu proper?  I frequently go to tuning and change things up, and there is a lot of travel right to left to right to make a single change.

Perhaps put a little gear icon on the Team bar.

**Comment by hook** [comment]
I'll look into it. Right now I have all page swaps inside tabs (add player, edit guide, etc.) in the lower left, so I'd want to do something consistent interface-wise if I changed that.

**Comment by hook** [comment]
I might set up hotkeys so you can use shortcuts on desktop to speed things up. I think that's a good compromise.

Thoughts?

**Comment by JasonJW** [comment]
That could work. 
I don't have any issue with the Add Hero or Edit Guide buttons being in the lower left - especially since you don't necessarily Add heroes or Edit guides all that often.  But the build tuning, I tweak constantly.

**Comment by hook** [comment]
Okay, so I've set up ctrl-b or apple-b to build teams and you can use history forward/backward (alt-left/right in lots of browsers) to go between the team screens. This should be a good workable solution.

**Comment by JasonJW** [comment]
ctrl-b does build teams, but I still have quite the mouse travel to switch build presets.
