### ISSUE TITLE
Bug in crit rate calculation ?

### ISSUE THREAD

**Issue by vinnytroia** [hook/champions#61]
If: 
1) a 4* Juggernaut + a 4* Colossus = 14% Crit rate
2) a 5* Juggernaut + a 4* Colossus = 14% crit rate 
then why doesn't a 4* Jugg + 5* Jugg + 4* Coll = 28% ?

**Comment by hook** [comment]
From Juggernaut to Colossus = 7%
From Juggernaut to Colossus = 7%
From Colossus to Juggernaut = 7%

You don't get to double up the from-to, so you get a max of 3x crit with this combination.
