### ISSUE TITLE
Crossbones doesn't export to "Alliance Tool"

### ISSUE THREAD

**Issue by Alsciende** [hook/champions#62]
My roster includes a 4\* Crossbones. When exported to frogspawn's tool, he was replaced by ~~an "Unused champion"~~ an unknown champion (identity is "None").

**Comment by hook** [comment]
Thanks I should update ids!

**Comment by hook** [comment]
hey @Alsciende can you verify if this works now?

**Comment by Alsciende** [comment]
Still no dice. The import data is

> csv_string=Id%2CStars%2CRank%2CLevel%2CAwakened%2CPi%2CRole%0D%0A%22crossbones%22%2C4%2C1%2C1%2C0%2C0%2C

but the Alliance Tool shows "Unused Champions" instead of "Crossbones".

**Comment by hook** [comment]
It's probably on his side of others work, since i just updated id mappings, so I'm sending the data the way he would be expecting it.
