### ISSUE TITLE
Add Quake Synergies

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#72]
Synergy bonuses

- Enemies (Critical Rate): Iron Patriot OR Crossbones
- Rivals (Critical Damage): Karnak or Blackbolt

-NEW-

- S.H.I.E.L.D. Agents (Ability Accuracy): Hawkeye
-- This synergy works with the whole team, and only affects the accuracy of status effects.  Hawkeye's Hemorrhage, or Iron Man's Armor Ups will trigger more often.

- S.H.I.E.L.D. Clearance Lv. 10 (Ability Potency): Black Widow [This ability effects only Black Widow and Quake]
-- Potency means the overall strength of the status effect. A stun will last longer, and have a higher chance to activate.  Black Widow's Subtlety is also affected if you don't have her at sig 99.

**Comment by hook** [comment]
I'll get that in later today

**Comment by hook** [comment]
Added effect types and synergies
