### ISSUE TITLE
BP-CW 4* bad prestige

### ISSUE THREAD

**Issue by Geeo** [hook/champions#75]
The prestige for 4\* BP-CW is not good (too low).

**Comment by hook** [comment]
I've updated prestige values, is it okay now?

**Comment by Geeo** [comment]
BP-CW still is a bad PI.

**Comment by hook** [comment]
Can you should me the current vs expected in a screenshot or something?

**Comment by Geeo** [comment]
BP-Civil War 4* 3/30 with sig level 20 should be 2239 PI, and it’s 1599 with you tool.

Best

Geoffrey

**Comment by hook** [comment]
Got it, there was an id mismatch.

**Comment by nipunk123** [comment]
Hey

Prestige numbers dont seem right for quake n ghost rider 4*
