### ISSUE TITLE
Synergy Bonus

### ISSUE THREAD

**Issue by PaeNiCII** [hook/champions#81]
first is a Line group for help ? test

4\* Witch 
Friends Lv. 3: +6% / Cpt or Ms Marvel
Enemies Lv. 3: +7% / Phoenix (New)
Romance Lv. 3: +5% / Vision
Teammates  Lv. 3: +5% / Ant-Man

4\* Thor
Friends Lv. 3: +6% / Dr. Strange
Friends Lv. 3: +6% / Ironman
Enemies Lv. 3: +7% / Jugger

Many Champs need a Fix

**Comment by hook** [comment]
Are these the current values or what they should be?
