### ISSUE TITLE
Add Ghost Rider

### ISSUE THREAD

**Issue by J-Stew-55** [hook/champions#85]
New champ Ghost Rider needs to be added to the 3_, 4_ and 5\* line up.

**Comment by hook** [comment]
was on vacation all last week, ill get it in tonight!

**Comment by hook** [comment]
Turns out halloween was busier than I thought, I'll get it in today for sure!

**Comment by J-Stew-55** [comment]
He looks good, but his PI is off (too low). I notice this is common with the newer champs. Is it a calculation issue?

**Comment by hook** [comment]
Yes newer champs dont have the right range of submitted data to calculate PI properly.
