### ISSUE TITLE
Thor - Wrong Synergies

### ISSUE THREAD

**Issue by jlueg** [hook/champions#86]
Hope you can fix Thor... at the Moment he is wrongly synergied to Gamora.

Thor 4* Synergies:
Friends Lvl.3 - Dr.Strange - +6%Armor
Friends Lvl.3 - IronMan - +6% Armor
Enemies Lvl.3 - Juggernaut - +7% Crit Rate  ( was wrong Gamora....)

**Comment by hook** [comment]
Fixed
