### ISSUE TITLE
Missing heroes

### ISSUE THREAD

**Issue by frumplejoon** [hook/champions#87]
### 2* Dr. Strange
   **Synergies:**
   Teammates Lv. 1 (+3% perfect block chance) - Scarlet Witch

### 3* Dr. Voodoo
   **Synergies:**
   Teammates Lv. 2 (+4% perfect block chance) - Rogue
   Rivals Lv. 2 (+20% critical damage) - Dr. Strange

**Comment by hook** [comment]
Added
