### ISSUE TITLE
Beast synergy: Masterminds/Combo

### ISSUE THREAD

**Issue by BillyNate** [hook/champions#88]
One of Beast his synergies is listed as `combo`, while it should be `masterminds` according to [playcontestofchampions.com/champion-spotlight-beast](http://playcontestofchampions.com/champion-spotlight-beast/), just like Loki.
I don't own a 4-star Beast myself, so I can't double check it unfortunately.

**Comment by hook** [comment]
There are 2 synergy effects called `masterminds` but they are actually different, so i put the extra combo damage under another name. The loki `masterminds` is extra energy damage. It's stupid so i just worked around it :)
