### ISSUE TITLE
She-hulk lost synergy with daredevil

### ISSUE THREAD

**Issue by x0m9ik** [hook/champions#95]
She-hulk lost synergy with daredevil

**Comment by ezgoing77** [comment]
to be specific, it is netflix DD.

**Comment by ezgoing77** [comment]
Attaching the images of both 3 and 4 star she-hulk. 
![img_5005](https://cloud.githubusercontent.com/assets/25097212/21961375/476d4ec8-db43-11e6-9b83-caccd8d80b59.PNG)
![img_5006](https://cloud.githubusercontent.com/assets/25097212/21961376/47ca853e-db43-11e6-958b-f6d91384d6dd.PNG)
