### ISSUE TITLE
Wrong Synergy between Ant-Man 3* and Falcon 3*

### ISSUE THREAD

**Issue by TheTitoPlay** [hook/champions#96]
In Synergy Menu I have a Perfect Block synergy between Ant-Man 3* and Falcon 3* but there is no such synergy in game.

Thanks man I love your MCOC Tool it is so usefull :)

**Comment by TheTitoPlay** [comment]
I have 3* and 4* Falcon and only the 4* one has the Perfect Block synergy with Ant-Man and Hawkeye

**Comment by hook** [comment]
Can you provide a screenshot of the existing synergies for Falcon, I don't have one of him yet!

**Comment by TheTitoPlay** [comment]
My game is in French so i'm gonna translate it ;)
![screenshot_2017-01-18-14-45-46 1](https://cloud.githubusercontent.com/assets/24769922/22066428/436f0c84-dd8d-11e6-8103-624486a3a6d9.png)
![screenshot_2017-01-18-14-46-01 1](https://cloud.githubusercontent.com/assets/24769922/22066432/4a98fcae-dd8d-11e6-8d74-c9df12a1676c.png)
Falcon 4* Caps : +6% Armor
War Machine/Black Widow : +7% Critical Rate
Vison AoU/Black Panther AoU : +7% Critical Rate
Ant-Man/Hawkeye : +5% Perfect Block

![screenshot_2017-01-18-14-46-44 1](https://cloud.githubusercontent.com/assets/24769922/22066441/4fff5346-dd8d-11e6-8156-41125c3af604.png)
![screenshot_2017-01-18-14-46-51 1](https://cloud.githubusercontent.com/assets/24769922/22066445/559ea61c-dd8d-11e6-8e22-ec92e3408fb5.png)
Falcon 3* Caps : +5% Armor
War Machine/Black Widow : +6% Critical Rate
Vison AoU/Black Panther AoU : +6% Critical Rate
