### ISSUE TITLE
missing synergy between luke cage and original Daredevil

### ISSUE THREAD

**Issue by ezgoing77** [hook/champions#98]
as in the title.

**Comment by hook** [comment]
Do you know which stars this is valid for? Images would be best if possible

**Comment by ezgoing77** [comment]
Didn't realize the stars made a difference. This is only for 4-star Luke cage, the 3-star one doesn't have this synergy. See image
![img_5004](https://cloud.githubusercontent.com/assets/25097212/21961109/f2c3f536-db3b-11e6-941b-a9c7c51c9760.PNG)
