### ISSUE TITLE
2* Groot is missing

### ISSUE THREAD

**Issue by user23498723452** [hook/champions#99]
He was made available for some players but cannot be selected.

**Comment by hook** [comment]
Do you know his 2* synergies?

**Comment by user23498723452** [comment]
As in Labels?  

Inseparable Lv 1 - Rocket Raccoon  (+7 sepecial 3 damage)
Friends Lv 1 - Star-Lord (+4% armor)

**Comment by user23498723452** [comment]
Mine is duped to level 1.

PI = 258
Health [+17] 754
Attack [+27] 48

**Comment by hook** [comment]
Thanks I'll get on that tonight or tomorrow at the latest
